ecommerch/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('account.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart_view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/',views.remove_item_from_cart,name='remove-item'),
    path('increase-quantity/<int:pk>/',views.increase_cart,name='increase'),
    path('decrease-quantity/<int:pk>/',views.decrease_cart,name='decrease'),

    
]

templates/base.html
{% load cart_product %}
{% load logoinfo %}
{% load static %}
 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} {% endblock title %} </title>  

      <!-- fontawesome account link -->
      <script
      src="https://kit.fontawesome.com/a5158a1674.js"
      crossorigin="anonymous"
    ></script>
    <!-- fontawesome offline css  -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
    <!-- faveicon link -->
    <link
      rel="shortcut icon"
      href="{% static 'img/favicon.png"
      type="image/x-icon' %}"
    />
    <!-- bootstrap offline css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- owl offline css -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block hover %} {% endblock hover %}
    {% block footer_css %} {% endblock footer_css %}
  </head>
  <body>
    <!-- Navbar -->
    {% include 'components/navbar.html'  %}
    <!-- Navbar End -->
<!-- start logo and search section -->

<section class="search mb-4 ">

  {% if user.is_authenticated %}
  <div class="container">
    <div class="row">
        <!-- logo -->
        <div class="col-lg-3 mt-3">
          <a class="navbar-brand text-dark" href="#"> <img style="width: 200px; height: 40px; margin-left: 10px;" src="{{request|logo}}" alt=""> </a>
        </div>
        <!-- start search ber -->
     <div class="col-lg-6 mt-3">
        <div class="header-center" >
          <div class="header-search header-search-extended header-search-visible d-none d-lg-block">
        <a href="" class="search-toggle" role="button"><i class="icon-search"></i></a>
        <form action="" method="post">
          {% csrf_token %}
        <div class="header-search-wrapper search-wrajpper-wide">
        <div class="row">
          <div class="col-lg-9">
            <input type="search" name="search_product" class="form-control" id="q" placeholder="search product">
          </div>
          <div class="col-lg-2 " >
            <button class="btn btn-outline-success" type="submit">Search</button>
          </div>
        </div>
        </div>
        </form>
          </div>
        </div>
     </div>

<!-- start cart and count part -->
<div class="col-lg-3 mt-3">
  <!-- count -->
  <div class="count">
    <a href="" data-bs-toggle="modal" data-bs-target="#count" class="btn btn-outline-success border col-md-4 float-lg-end ">Count</a>
    <!-- Modal count -->
    <div class="modal fade" id="count" tabindex="-1" role="dialog" aria-labelledby="checkoutModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="checkoutModalLabel">
  Count</h5>
            <hr>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="m-2 p-3">
              <form action="/check-out" method="POST">
                  {% csrf_token %}
                  <div class="icon">
                    
                    {% if request.user.is_authenticated %}
  
                  <span>{{request.user|cart_count}}</span> 
                  {% else %}
                  <span>0</span>
  
                    {% endif%}
                  
                  </div>
              </form>
            </div>
          </div>
         
        </div>
      </div>
    </div >
  </div>

  <!-- cart -->
<div class="cart">
  <a href="#" data-bs-toggle="modal" data-bs-target="#cart" class="btn btn-outline-success border col-md-4 float-lg-end mx-3">cart</a>
    
  <!-- Modal cart -->
  <div class="modal fade" id="cart" tabindex="-1" role="dialog" aria-labelledby="ColorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ColorModalLabel">
  Total product, quantity & price</h5>
          <hr>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="m-2 p-3">
            <form action="/check-out" method="POST">
                {% csrf_token %}
                <div class="show_cart_items">  
                  {% if request.user.is_authenticated %}
                  {% if request.user|cart_view %}
                  {% for cart in request.user|cart_view %}
                <h5><a href="product.html">{{cart.item.name}}</a>
                
                </h5> 
                
                <span>{{cart.item.price}}</span> X <span>{{cart.quantity}}</span> = <span>{{cart.get_total}}</span> <span><a href="poduct.html">
                  <img style="width: 90px; height: 40px;" src="{{cart.item.image.url}}" alt="">
                </a></span>
                
                  {% endfor %}
                  {% endif %}
                  {% endif%}
                
                </div>
      
                <div class="total">
                  <span>Total</span>
                   {% if request.user.is_authenticated %}
                <span class="cart-total-price">Tk {{request.user|cart_total}}</span>
                   {% else %}
                  <span class="cart-total-price">0</span>
                   {% endif %}
                 </div>
    
                 <div class="cart_html">
                  <span><a class="btn mt-3 btn-primary" href="{% url 'order:cart' %}">view cart</a></span>  <span><a href=""></a></span>
                 </div>
            </form>
          </div>
        </div>
       
      </div>
    </div>
  </div >


</div>

</div>

</div>
    </div> 
    {% endif %}
    </section>

    <div class="container mx-5">{% block content %}{% endblock %}</div>

    <!-- Footer -->
    {% include 'components/footer.html' %}
    <!-- Footer End -->
  

 <!-- bootstrap javaScript css -->
 <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  </body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Login</h3>
<hr>

<div class="row">
  <div class="col-md-6 col-sm-12 mx-auto">
    <form action="{% url 'login' %}" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 col-sm-12 mx-auto">
          <div class="form-group my-2">
            <input type="text" name="username" class="form-control" placeholder="username" autocomplete="off" required>
          </div>
          <div class="form-group my-2">
            <input type="password" name="password" class="form-control" placeholder="password" autocomplete="off" required>
          </div>

          <button type="submit" class="btn btn-success my-3">Login</button>

        </div>
      </div>

    </form>
  </div>
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block title %} Profile || Ecommerch {% endblock title %}
<div class="container">
    
{% block content %}

<main class="main">
<!-- 
   start page head  -->
<div class="text-center" style="background-image: url();">
<div class="container">
<h1 class="page-title">MY Account</h1>
</div>
</div>
<!-- start navber -->
<nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
<div class="container">
    <ol class="breadcrumb">
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item"><a href="#">Shop</a></li>
<li class="breadcrumb-item"><a href="#">My Account</a></li>
    </ol>
</div>
</nav>

<!-- start left icon -->
        <div class="container">
            <div class="row">
                <!-- start left site -->
                <aside class="col-md-4 col-lg-3">
                    <ul>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary  " type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExampleDashboard" aria-expanded="false" aria-controls="collapseWidthExample">
                                Dashboard
                            </button>                        </li>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExampleOrders" aria-expanded="false" aria-controls="collapseWidthExampleOrders">
                                Orders
                            </button>                        </li>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
                                Download
                            </button>                        </li>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExampleAddresses" aria-expanded="false" aria-controls="collapseWidthExampleAddresses">
                                Addresses
                            </button>                        </li>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExampleAccount_Details" aria-expanded="false" aria-controls="collapseWidthExampleAccount_Details">
                                Account Details
                            </button>                        </li>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary mt-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
                                Sign out
                            </button>                        </li>
                    </ul>                
                </aside>         

                <!-- start right site -->

                <div class="col-lg-9 col-md-8">

                    <div class="Dashboard">
                        <div class="collapse collapse-horizontal" id="collapseWidthExampleDashboard">
                        <div class="row">
                         <div class="col-lg-6 ms-5  d-flex flex-column justify-content-center align-items-center overflow-hidden">
                            <div class="profile_image">
                               <img src="{{user.profile.image.url }}" class=" rounded" alt="" style="width:360px; height: 200px;">
                            </div>
                            <div class="profile-info mt-4">
                                <h4>{{user.profile.full_name}}</h4>
                                <span>{{user.profile.address}}, {{user.profile.city}}, {{user.profile.country}}.</span> <br>
                                <span>Mobile: {{user.profile.phone}}</span>

                            </div>

                         </div>
                        </div>
                        </div>
                      </div>


                      <div class="orders">
                        <div class="collapse collapse-horizontal" id="collapseWidthExampleOrders">
                          <div class="card card-body"> 
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Id</th>
                                        <th scope="col">Products</th>
                                        <th scope="col">Payment Id</th>
                                        <th scope="col">Order Id</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                <tr>
                                    <td scope="row">{{order.id}}</td>
                                    <td >
                                        {% for order_item in order.orderitems.all %}
                                        <ul>
                                            <li>{{order_item}}</li>
                                        </ul>
                                        {% endfor %}
                                    </td>
                                    <td>{{order.paymentId}}</td>
                                    <td>{{order.orderId}}</td>
                                </tr>
                                    {% endfor %}
                                </tbody>
                                </table>
                          </div>
                        </div>
                      </div>
                     
                    <div class="Addresses">
                        <div class="collapse collapse-horizontal" id="collapseWidthExampleAddresses">
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="card card-body" >
                                    <h3>Billing Address</h3>
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {{billingaddress}}
                                        <br>
                                        <input class="btn btn-primary mt-2" type="submit" value="save address">
                                    </form>
                                  </div>
                            </div>
                            <div class="col-lg-6">
                                ff
                            </div>
                        </div>
                        </div>
                      </div>
                     
                     
                      <div class="AccountDetails">
                        <div class="collapse collapse-horizontal" id="collapseWidthExampleAccount_Details">
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="card card-body" >
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {{ProfileForm}}
                                        <br>
                                        <input class="btn btn-primary mt-2" type="submit" value="save address">
                                    </form>
                                  </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="card card-body" >
                               gg
                                  </div>
                            </div>
                        </div>
                        </div>
                      </div>
                  

                  

          

                </div>
    </div>
        </div>


</main> 


{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Register</h3>
<hr>

<div class="row">
  <div class="col-md-6 col-sm-12 mx-auto">
    <form action="{% url 'register' %}" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 col-sm-12 mx-auto">
          <div class="form-group my-2">
            <div class="row">
              <div class="col-md-6">
                <input type="text" name="first_name" class="form-control" placeholder="first name" required autocomplete="off">
              </div>
              <div class="col-md-6">
                <input type="text" name="last_name" class="form-control" placeholder="last name" required autocomplete="off">
              </div>
            </div>
          </div>
          <div class="form-group my-2">
            <input type="text" name="username" class="form-control" placeholder="username" required autocomplete="off">
          </div>
          <div class="form-group my-2">
            <input type="email" name="email" class="form-control" placeholder="email" required autocomplete="off">
          </div>
          <div class="form-group my-2">
            <input type="password" name="password1" class="form-control" placeholder="password" required autocomplete="off">
          </div>
          <div class="form-group my-2">
            <input type="password" name="password2" class="form-control" placeholder="Confirm password" required autocomplete="off">
          </div>

          <button type="submit" class="btn btn-success my-3">Register</button>

        </div>
      </div>

    </form>
  </div>
</div>
{% endblock %}