ecommerch/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('account.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart_view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/',views.remove_item_from_cart,name='remove-item'),
    path('increase-quantity/<int:pk>/',views.increase_cart,name='increase'),
    path('decrease-quantity/<int:pk>/',views.decrease_cart,name='decrease'),

    
]

payment/urls.py
from django.urls import path
from payment import views


app_name = 'payment'
urlpatterns = [
    path('checkout/', views.CheckoutTemplateView.as_view(), name='checkout'),
]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('index', views.HomeListView.as_view(), name='index'),
    path('product/<slug:slug>/', views.ProductDeleteView.as_view(), name='product_details'),
]

store/models.py
from django.db import models
#slug
from django.template.defaultfilters import slugify
#কারেন্ট প্রোডাক্টটিকে detail.html e শো করতে 
from django.urls import reverse
# for user
from django.contrib.auth.models import User 

# Create your models here.

class Category(models.Model):
    name =models.CharField(max_length=50, blank=False, null=False)
    image = models.ImageField(upload_to='category', blank=True, null=True)
    parent =models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created']
        verbose_name_plural ='Categories'
    

class Product(models.Model):
    name =models.CharField(max_length=250, blank=False, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_desc =models.CharField(max_length=250, verbose_name='short Description')
    description =models.TextField(max_length=1000, verbose_name='Description')
    image = models.ImageField(upload_to='product', blank=False, null=False)
    price = models.FloatField()
    old_price= models.FloatField(default=0, blank=True, null=True)
    is_stock = models.BooleanField(default=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created']
    
    def get_product_url(self):
        return reverse('store:product_details', kwargs={'slug': self.slug})
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class ProductImages(models.Model):
    Product = models.ForeignKey(Product,on_delete=models.CASCADE)
    image = models.FileField(upload_to='product_gallery')
    created = models.DateTimeField(auto_now_add=True)
        
    def __str__(self):
        return str(self.Product.name) 
    


# manager for product variation manager

class variationManager(models.Manager):
    def sizes(self):
        return super(variationManager, self).filter(variation='size')
    
    def colors(self):
        return super(variationManager, self).filter(variation='color')

#for product variation. it means product size and color

VARIATIONS_TYPE = (
    ('size', 'size'),
    ('color', 'color'),
)

class VariationValue(models.Model):
    variation = models.CharField(max_length=100, choices=VARIATIONS_TYPE)
    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = variationManager()
    
    def __str__(self):
        return self.name
    
#for show daynamic data in index page
class Banner(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='banner')
    image = models.ImageField(upload_to='banner')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
      
    def __str__(self):
        return self.product.name
    
#for logo
# User =  get_user_model()
class Mylogo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='logo')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.image)
    
#for favicon
class MyFavicon(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='logo')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.image)

    
    

store/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView,TemplateView
# Create your views here.

#product model
from store.models import Category, Product, ProductImages, Banner


class HomeListView(TemplateView):
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['banners'] = Banner.objects.filter(is_active=True).order_by('-id')[:5]
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        category_id = request.GET.get('category_id')  # Get the category ID from the URL parameter
        if category_id:
            # If category_id is provided, filter products by the selected category
            products = Product.objects.filter(category_id=category_id).order_by('-id')
        else:
            # Otherwise, show all products
            products = Product.objects.all().order_by('-id')
        context['products'] = products
        return render(request, self.template_name, context)
    
      #show search data
    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search_product = request.POST.get('search_product')
            products = Product.objects.filter(name__icontains=search_product).order_by('-id')

            context = {
                'products': products
            }
            return render(request, 'store/index.html', context)


#for multiple data show.    
class ProductDeleteView(DetailView):
    model = Product
    template_name = 'store/product.html'
    context_object_name = 'item'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_images'] = ProductImages.objects.filter(Product=self.object.id)
        return context
# def product_details(request, pk):
#     item = Product.objects.get(id=pk)
#     photos = ProductImages.objects.filter(product=iterm).order_by('-created)
#     context = {
#         'item': item,
#          'photos': photos,
#     }
#     return render(request,'store/product.html',context)
#     এটি উপরের ক্লাসবেজভিউ  এর ফাংশনভিউ

templates/store/cart.html
{% extends 'base.html' %}
{% block title %} Cart Page || Ecommerch {% endblock title %}
{% block content %}

<section class="order_view_section mt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <!-- order_part -->
                <div class="order_part rounded py-2" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
                    <!-- heading -->
                    <p  class="display-6" style="text-align: center; font-style: italic; font-weight: 400;"> Your Orders</p>
                    <!-- order_view -->
                    <table class="table">
                        <thead>
                            <tr>
                               <th scope="col">Sno</th>
                                <th scope="col">Image</th>
                                <th scope="col">Product</th>
                                <th scope="col">size</th>
                                <th scope="col">color</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- card item -->
                            {% for cart in carts %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td><a href="#"><img style="width:100px; height: 50px;" src="{{cart.item.image.url}}" alt=""></a></td>
                                <td>{{cart.item.name}}</td>
                                <td>{{cart.size}}</td>
                                <td>{{cart.color}}</td>
                                <td>
                                    {% if cart.variation_single_price %}
                                    ${{cart.variation_single_price}}
                                    {% else %}
                                    ${{cart.item.price}}
                                    {% endif %}
                                </td>
                                <!-- quantity -->
                                <td>
                                    <div class="quantity">
                                    <a href="{% url 'order:decrease' pk=cart.item.pk %}" class="btn btn-light">-</a>
                                    <span>{{cart.quantity}}</span>                           
                                    <a href="{% url 'order:increase' pk=cart.item.pk %}" class="btn btn-light">+</a>
                                </td>
                                <!-- card total -->
                                <td>
                                    {% if cart.variation_total %}
                                    ${{cart.variation_total}}
                                    {% else %}
                                    {{cart.get_total}}tk.
                                    {% endif %}
                                </td>
                                <!-- delet card item -->
                                <td>
                                    <a href="{% url 'order:remove-item' pk=cart.item.pk %}" class="btn">x</a>
                                </td>
                            
                            {% endfor %}
                        </tbody>                      
                    </table>
                </div>

                <!-- coupon_code_part -->
                <div class="couponcode">
                  <div class="col-lg-6 rounded mt-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
                    <form action="" method="POST" class="ms-5 p-4">
                        Coupon 
                        {% csrf_token %}
                        {{ coupon_form }}
                        <button type="submit" >></button>
                    </form>
                  </div>
                </div>
            </div>

            <!-- cart total section -->
            <div class="col-lg-3 mx-auto ps-4 pt-4" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
                <h3>Cart Total</h3>
<table class="table">
<tbody>
    <tr>
        <td>subtotal:</td>
        <td>{{order.get_totals}}</td>
    </tr>
    <tr>
        <td>Total:</td>
        <td>
            {% if total_price_after_discount %}
            {{total_price_after_discount}}
            {% else %}
            ${{order.get_totals}}
            {% endif %}
        </td>
    </tr>
</tbody>
</table>
<a href="{% url 'payment:checkout' %}" class="btn btn-outline-primary-2 btn-info mt-3 btn-order btn-block " style="font-style: italic; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">PROCEED TO CHECKOUT</a>

            </div>
        </div>
    </div>
</section>



  <!-- hover  -->
  {% block hover %}
<!-- <style>
      .couponcode:hover {
          transform: scale(1.05);
          transition: transform cubic-bezier(0.39, 0.575, 0.565, 1) 1s;

        } 
</style> -->
{% endblock hover %}

{% endblock content %}

templates/store/checkout.html
{% extends 'base.html' %}
{% block title %} Checkout Page || Ecommerch {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7 mx-3 border rounded">
     <form action="" method="post" class="mt-3">
        {% csrf_token %}
        <div class="billng_address" >
            {{billing_address.as_p}}
         </div>
   

        </div>

        <!-- start total of orders -->
        <div class="col-lg-4 mx-4 border rounded ">

            <table class="table mt-3">
<thead>
    <tr>
        <th>Product</th>
        <th>Total</th>
    </tr>
</thead>

                <tbody>
                    {% for item in order_item %} 
                    <tr>
                        <td><a href="" style="text-decoration: none;">{{item.item.name}}</a></td>
                        {% if item.get_total %}
                            <td>${{item.get_total}}</td>
                        {% elif item.variation_single_price %}
                            <td>${{item.variation_single_price}}</td>
                        {% elif item.variation_total %}
                            <td>${{item.variation_total}}</td>
                        {% endif %}
                    </tr> 
                    {% endfor %}     
                    
                    <tr>
                        <td>Subtotal:</td>
                        <td>{{order_total}}</td>
                    </tr>
                    <tr>
                        <td>Shipping:</td>
                        <td>Free</td>
                    </tr>
                    <tr>
                        <td>Total</td>
                        <td>{{order_total}}</td>
                    </tr>
                </tbody>

                </table>

                <div class="accordion-summary" id="accordion-payment">
                    <div >
                        {{payment_method.as_p}}

                    </div>
                    <button type="submit" class="btn btn-outline-primary">
                        <span class="btn-text">Place Order</span>
                        <!-- <span class="btn btn-hover-text">Proceed to Checkout</span> -->
                    </button>
                    
                </div>
            </form>
        </div>
    </div>


</div>

{% endblock content %}

<!-- for paypal  -->
{% block paypal %} 
<script 
src="https://www.papal.com/sdk/js?client-id=YOUR_CLIENT_ID"
> </script>
{% endblock paypal %}

templates/store/index.html
{% extends 'base.html' %}

{% block title %} E-Store || Ecommerch {% endblock title %}
<div class="container"> 
{% block content %}



   <!-- start category and banner section  -->
   <section class="catagory_and banner">
    <div class="container">
      <div class="row">

        <!-- start category part -->
   <div class="col-lg-3">
     <nav class="navbar navbar-dark">
         <div class="container">
             <button class="navbar-toggler text-dark px-4 py" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
                 <h4> Category
                     <span class="navbar-toggler-icon"></span>
                 </h4>
             </button>
         </div>
     </nav>
   
     <div class="collapse shadow" id="navbarToggleExternalContent">
         <div class="bg- p-4">
             <ul class="navbar-nav ms-auto mb-2 mb-lg-0 nav-link">
                <!-- Add the link for displaying all products -->
                <li class="item-lead nav-link">
                  <a href="/" class="text-decoration-none fw-bold">All Products</a>
                </li>
                 {% for cat in categories %}
                 {% if cat.children.all %}
                 <li class="item-lead nav-link">
                     <a href="?category_id={{ cat.id }}" class="text-decoration-none fw-bold">{{ cat.name }}</a>
                     <ul class="text-decoration-none">
                         {% for subcategory in cat.children.all %}
                         <li style="list-style: none;">
                             <a class="text-decoration-none fw-bold text-dark ms-4" href="?category_id={{ subcategory.id }}">{{ subcategory.name }}</a>
                         </li>
                         {% endfor %}
                     </ul>
                 </li>
                 {% endif %}
                 {% endfor %}
             </ul>
         </div>
     </div>
   </div>
   

        <!-- start banner part -->
        <div class="col-lg-6 rounded d-flex flex-column justify-content-center align-items-center overflow-hidden " style=" height: 250px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); ">
          <div id="banner-carousel" class="carousel slide " data-bs-ride="carousel">
            <ol class="carousel-indicators">
              {% for banner in banners %}
              <li data-bs-target="#banner-carousel" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
              {% endfor %}
            </ol>
            <div class="carousel-inner">
              {% for banner in banners %}
              <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img  class="d-block img-fluid ms-2 py-3"  src="{{banner.image.url}}" alt="{{banner.product.name}}" style="width: 520px; height: 250px;">
                <div class="carousel-caption d-none d-md-block">
                  <h5 class="intro-subtitle text-primary">New Arrival</h5>
                  <h1 class="intro-title">{{banner.product.name}}</h1>
                  <h3><sup>Today</sup><span class="text-primary"> ${{banner.product.price}}</span></h3>
                  <a href="" class="btn btn-primary btn-round">
                    <span>Shop more</span>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#banner-carousel" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#banner-carousel" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>

      </div>
    </div>
   </section>


<!-- start products section -->
<section class="product_section section mt-5" >
  <div class="container">
    <div class="row">
      {% for product in products %}
      <div class="product col-md-2 mb-3   justify-content-center " >
        <div class="py-2 text-center" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
          <img style="width: 130px; height: 70px;" src="{{product.image.url}}" alt="Not Found" /><br>
          <span><a class="fw-bold" href="{{product.get_product_url}}" style="text-decoration: none;">{{product.name}}</a></span><br>
          <span>price: {{product.price}} tk.</span><br>
          <span>{% if product.old_price %}Old price: <del>{{product.old_price}}</del> tk.{% endif %}</span>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- hover  -->
  {% block hover %}
  <style>
    .product:hover {
      transform: scale(1.05);
      transition: transform cubic-bezier(0.39, 0.575, 0.565, 1) 1s;
    }
  </style>
  {% endblock hover %}
</section>


{% endblock %}

</div>

templates/store/product.html
{% extends 'base.html' %}


<div class="container">
    
{% block content %}


<div class="col-lg-12 ms-5 mt-4">
  <div class="row 
  " >

  <div class="col-md-2 " style="width: 150px;" >
    <div class="row">
      {% for product_image in product_images %}

  <div class=" sub-image rounded  h-50 mt-2" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
      
<a  href="{{product_image.image.url}}" data-image="{{product_image.image.url}}" data-zoom-image="{{product_image.image.url}}"><img 
  class="-image-top active w-100 h-50 my-2"
  src="{{product_image.image.url}}"
  alt="Not Found"
/></a>
    </div>
    {% endfor %} 
    </div>
  </div>

  
    <div class=" col-lg-7 ms-auto" style="width: 500px; height: 330px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); ">
      <a  class=" " href="{{item.image.url}}">
        <img  class="p-3 pt-4 w-100 "
      src="{{item.image.url}}"
      alt="Not Found"
    />
      </a>
    </div>


   <div class=" mx-auto rounded p-4 col-lg-3 " style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); ">
    
    <div class="product_details mx-2">
      <h3 class="card-title">{{item.name}}</h3>
    <h3 class="card-title">{{item.price}}.tk</h3>
    <div class="card-title"> {% if item.old_price %} Old price: <del> {{item.old_price}} </del> tk. {% endif %} </div>
    <span>category:<a style="text-decoration: none;" href="#">{{item.category}}</a> </span>
    </div>


<!-- this is the part of product variation  -->

<form class="mt-2" action="{% url 'order:add_to_cart' pk=item.pk %}" method="post"> 

  {% csrf_token %}

  
 <div class="product_variation_size_color_quantity">

  <div class="row product variation_size mt-2">

    <div class="col-md-12">
           {% if item.variationvalue_set.sizes %}
   
          <div class="row " >
          <div class="col-lg-4" >
            
           <label for="size">Size</label>
          </div>
     
          <div class="col-lg-2" >
            
           <select name="size" id="size">
             <option value="#" selected="selected">Select a size</option>
             {% for item_variation in item.variationvalue_set.sizes %}
             <option name="size" value="{{item_variation.name}}">{{item_variation.name}}</option>
             {% endfor %}
           </select>
         </div>
   
          </div>
   
          {% endif %}
        </div>
      </div>
   
      <div class="row product variation_color mt-2">
   
       <div class="col-md-12">
         {% if item.variationvalue_set.colors %}
   
        <div class="row " >
        <div class="col-lg-4" >
          
         <label for="color">Colors</label>
        </div>
   
        <div class="col-lg-2" >
          
         <select name="color" id="color">
           <option value="#" selected="selected">Select a color</option>
           {% for item_variation in item.variationvalue_set.colors %}
           <option name="color" value="{{item_variation.name}}">{{item_variation.name}}</option>
           {% endfor %}
         </select>
       </div>
   
        </div>
   
        {% endif %}
      </div>
    </div>
   
    <div class="row product variation_qty mt-2">
   
      <div class="col-md-12">
  
       <div class="row " >
       <div class="col-lg-4" >
         
        <label for="qty">Qty</label>
       </div>
  
       <div class="col-lg-2" >

<div >
  <input style="width: 100px;" type="number" id="qty" name="quantity" value="1" >

</div>
      </div>
  
       </div>
  
     </div>
   </div>

   <div class="add-to-cart mt-5">
 <button type="submit" class="btn btn-primary ">add to cart</button>
  </div>  
 </div>
    </form>
    

   </div> 
  

  </div>



<!-- product description -->
  <div class="row m-4 " >
    <div class="col-9 ms-4 py-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); ">
     <h3 class="mt-4 ms-4"> <h3>product description:</h3> {{item.description}}</h3>
    </div>
  </div>
</div>


<!-- hover section -->

{% block hover %}
<style>
      .sub-image:hover {
          transform: scale(1.05);
          transition: transform cubic-bezier(0.39, 0.575, 0.565, 1) 1s;

        } 
</style>
{% endblock hover %}

{% endblock %}

</div>