ecommerch/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('account.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart_view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/',views.remove_item_from_cart,name='remove-item'),
    path('increase-quantity/<int:pk>/',views.increase_cart,name='increase'),
    path('decrease-quantity/<int:pk>/',views.decrease_cart,name='decrease'),

    
]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('index', views.HomeListView.as_view(), name='index'),
    path('product/<slug:slug>/', views.ProductDeleteView.as_view(), name='product_details'),
]

templates/components/footer.html
<!-- Start Footer -->
<footer class="footer-area" style="margin-top: 90px; box-shadow: 0px 8px 20px rgba(0.3, 0.30, 0.30, 0.3); border-top: #043873; ">
  <!-- footer top -->
  <div class="footer-top ">
      <div class="container">
          <div class="row">
              <div class="col-lg-3 ">
                  <div class="footer-about ">
                      <img class="w-50" src="/static/img/nav_img.png" alt="">
                      <p>But i must explain to you all this mistaken
                          idea of dencouncing pleasure.</p>
                  </div>
              </div>
              <div class="col-lg-2 "><div class="footer-top-link">
                  <h3>Quick Links</h3>
                  <ul>
                      <li><a href="">About Our Company</a></li>
                      <li><a href="">Services WE provide</a></li>
                      <li><a href="">Career & Opportunity</a></li>
                      <li><a href="">Privacy & policy</a></li>
                      <li><a href="">Contact US</a></li>
                  </ul>
              </div></div>
              <div class="col-lg-2"><div class="footer-top-link">
                  <h3>Company</h3>
                  <ul>
                      <li><a href="">About Company</a></li>
                      <li><a href="">Our Testimonials</a></li>
                      <li><a href="">Latest News</a></li>
                      <li><a href="">Our misson</a></li>
                      <li><a href="">Get a free Quot</a></li>
                  </ul>
              </div></div>
              <div class="col-lg-2 "><div class="footer-top-link">
                  <h3>Contact us</h3>
                  <address>
                      Sagrada Familia, Herba <br>Street Front USA <br> brandoxide@gmail.com <br> <i class="fa-solid fa-phone me-2"></i> 002-568423591
                  </address>
              </div></div>
              <div class="col-lg-3 ">
                  <div class="footer-social footer-top-link extra-social-design ">
                      <h3>Follow Us</h3>
                      <ul>
                          <li><a href=""><i class="fa-brands fa-facebook"></i></a></li>
                          <li><a href=""><i class="fa-brands fa-square-twitter"></i></a></li>
                          <li><a href=""><i class="fa-brands fa-instagram"></i></a></li>
                          <li><a href=""><i class="fa-brands fa-linkedin"></i></a></li>    
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <!-- footer bottom -->
  <div class="footer-bottom">
      <div class="container">
          <div class="row">
              <div class="footer-bottom-tex">
                  <p class="m-0">Developed by MD. SHAHIN | <a href="#">Brandoxide</a>.all right reserved & Copyright @ 2023.</p>
              </div>
          </div>
      </div>
  </div>

</footer>



{% block footer_css %}
  
  
<style>
  
/* Footer css */
.footer-area{
background-color: #f8f8f8;
}
.footer-top{
padding-top: 70px !important;
padding-bottom: 30px;
}

.footer-top h3{
padding-bottom: 15px;
}

.footer-about img{
margin-bottom: 15px;
}

.footer-top-link h3{
font-size: 20px;
text-transform: capitalize;
}

.footer-top-link ul{
margin: 0;
padding: 0;
list-style: none;

}

.footer-top-link li a{
text-decoration: none;
display: inline-block !important;
padding: 2px;
font-size: 16px;
color: #646464;
transition: .3s;
}

.footer-top-link li a:hover{
/* background-color: #043873 ; */
/* color: #ffff; */
color: #caa892;
border-radius: 5px;
}

.footer-social li{
display: inline-block;
margin-right: 5px;
}
.footer-social li a{
background-color: #d5d5d5;
width: 30px;
height: 30px;
display: flex !important;
justify-content: center;
align-items: center;
border-radius: 50px;
color: #ffff;
transition: .5s;

}

.footer-social li a:hover{
background-color: #043873;

}

.extra-social-design li a:hover{
background-color: #043873 !important;
color: #ffff;
border-radius: 5px;

}

.footer-bottom{
border-top: 1px solid #c4c4c4;
padding: 10px 0;
align-items: center;
text-align: center;
}

.footer-bottom-tex a{
text-decoration: none;
color: #caa892;
}


/* RESPONSIVE CSS */

@media (max-width: 991px){

/* header css 991 */

.header-area .nav-item {
    margin-left: 20px !important;
    margin-top: 4px;
 }
 

 .header-area .nav-item:last-child .nav-link{
    margin-left: 0;
    margin-top: 10px;
    width: 100px;
 }



    /* footer css 991 */

.footer-about{
text-align: center;
}

.footer-top{
padding-top: 40px !important;
}
.footer-top-link{
text-align: center;
margin-top: 30px;
}
.footer-top-link h3{
padding-bottom: 0 !important;
}
.footer-social h3{
padding-bottom: 15px !important;
}
}
</style>

{% endblock footer_css %}
<!-- End Footer -->

templates/components/navbar.html
{% block logoinfo_from_navbar %}
 {% load logoinfo %}

 <!-- Start Header -->
<header class="header-area mb-3 " style="box-shadow: 0px 8px 20px rgba(0.3, 0.30, 0.30, 0.3); ">
  <div class="container ">
      <nav class="navbar navbar-expand-lg ">
          <a class="navbar-brand" href="#">
            <!-- <img style="height: 40px;" src="" alt="image"> -->
            <h5>Web Development</h5>
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <!-- for menu ber image -->
            <span>
              <i class="fa-solid fa-bars"></i>
            </span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="header-ul ms-auto">
                <ul class="navbar-nav  " style="text-transform: uppercase;">
                  {% if user.is_authenticated %}
                  
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'store:index' %}">Home</a>
                  </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">PROJECT</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        SERVICES
                      </a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="#"> dropdown one</a></li>
                          <li><a class="dropdown-item" href="#">dropdown two</a></li>
                        </ul>
                    </li>
  
                  {% if user.is_authenticated %}
                  <li class="nav-item ">
                    <a class="nav-link" href="{% url 'profile' %}" >profile</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'logout' %}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item" style="text-transform: uppercase;">
                    <a class="nav-link" aria-current="page" href="{% url 'register' %}">Register</a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'login' %}">Sign Up</a>
                  </li> 
                  {% endif %}  
                </ul>
            </div>
          </div>
        
      </nav>
  </div>
</header>
        
<!-- End Header -->


{% endblock logoinfo_from_navbar %} 